# Azure Web Apps Deployment for Cobalt Project
# Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - youtube-cobalt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out code from repository
      - uses: actions/checkout@v4

      # Set up Node.js version
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Keep the specified version from the original YAML

      # Install pnpm (Cobalt uses pnpm instead of npm)
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies and prepare for deployment
      - name: Install dependencies
        run: |
          cd api/src
          pnpm install

      # Package the app for deployment
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip api/

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Unzip artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_00920CCCBBB34C99A98AB015C09D6D1A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_32195A01AD3D4D0CBE25F0012673C559 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BF53F719A952444B9B8D4AB5DDBDD887 }}

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'youtube-cobalt'
          slot-name: 'Production'
          package: .
